### ISSUE TITLE
Checklist Custons PVP needed.

### ISSUE THREAD

**Issue by Raneves** [L2JServer-PVP/L2JServer#5]
- [ ] Captcha on login (bot protection)
- [ ] Newbie starting in unique place
- [ ] Make Noble player by voice command .nobles
 - messages item needed
 - messages already noble
